script.reload("scripts/render/render_utility.lua")
GenerateCSMLevels = 4
function Build(_ARG_0_)
  SCREEN_W = GetSurfaceWidth(_ARG_0_, "framebuffer0")
  SCREEN_H = GetSurfaceHeight(_ARG_0_, "framebuffer0")
  CreateCSM(_ARG_0_, GenerateCSMLevels, 1024)
  ApplySceneParams(_ARG_0_)
  CreateReflectionTexture(_ARG_0_)
  SetFrameBufferObjectOnce(_ARG_0_, "framebuffer0", "depthstencil", "all", 0, 0, 0, 0)
  SetFrameBufferObject(_ARG_0_, "framebuffer0", "depthstencil", "none", 0, 0, 0, 0)
  SetViewport(_ARG_0_, 0, 0, SCREEN_W, SCREEN_H)
  SetCurrentCamera(_ARG_0_, "main")
  AutoSetAspect(_ARG_0_)
  Zpass(_ARG_0_, "depthbuffer0", "depthstencil", "main")
  RenderMain(_ARG_0_, "framebuffer0", "depthstencil")
  SetFrameBufferObjectOnce(_ARG_0_, "backbuffer", "depthstencil", "color", 0, 0, 0, 0)
  SetFrameBufferObject(_ARG_0_, "backbuffer", "depthstencil", "none", 0, 0, 0, 0)
  ResetViewport(_ARG_0_)
  CopyTexture(_ARG_0_, "framebuffer0")
  Render2D(_ARG_0_)
end
