function Build(_ARG_0_)
  SCREEN_W = GetSurfaceWidth(_ARG_0_, "framebuffer0")
  SCREEN_H = GetSurfaceHeight(_ARG_0_, "framebuffer0")
  ApplySceneParams(_ARG_0_)
  SetFrameBufferObject(_ARG_0_, "framebuffer0", "depthstencil", "all", 0, 0, 0, 0)
  SetViewport(_ARG_0_, 0, 0, SCREEN_W, SCREEN_H)
  SetCurrentCamera(_ARG_0_, "main")
  AutoSetAspect(_ARG_0_)
  SetConstantShader(_ARG_0_, "main", "simple", "DefaultTechnique")
  RenderWorld(_ARG_0_, "main")
  SetConstantShader(_ARG_0_, "main", "null")
  ResetViewport(_ARG_0_)
  ApplyDevice(_ARG_0_)
  SetFrameBufferObject(_ARG_0_, "backbuffer", "depthstencil", "all", 0, 0, 0, 0)
  CopyTexture(_ARG_0_, "framebuffer0")
  RenderDebug3DFont(_ARG_0_)
  RenderCSD(_ARG_0_)
  RenderDebug(_ARG_0_)
end
