script.reload("scripts/render/render_utility.lua")
function Build(_ARG_0_)
  SCREEN_W = GetSurfaceWidth(_ARG_0_, "framebuffer0")
  SCREEN_H = GetSurfaceHeight(_ARG_0_, "framebuffer0")
  CreateCSM(_ARG_0_)
  ApplySceneParams(_ARG_0_)
  SetFrameBufferObject(_ARG_0_, "framebuffer0", "depthstencil", "all", 0, 0, 0, 0, "4x")
  SetViewport(_ARG_0_, 0, 0, SCREEN_W, SCREEN_H)
  SetCurrentCamera(_ARG_0_, "main")
  AutoSetAspect(_ARG_0_)
  SetZMode(_ARG_0_, "lessequalon")
  LockZMode(_ARG_0_, "true")
  SetBlendMode(_ARG_0_, "opaque")
  LockBlendMode(_ARG_0_, "true")
  RenderWorld(_ARG_0_, "main", "all", "opaque")
  RenderWorld(_ARG_0_, "main", "all", "punchthrough")
  LockZMode(_ARG_0_, "false")
  LockBlendMode(_ARG_0_, "false")
  RenderWorld(_ARG_0_, "main", "all", "transparent")
  SetFrameBufferObjectOnce(_ARG_0_, "backbuffer", "null", "color", 0, 0, 0, 0)
  SetFrameBufferObject(_ARG_0_, "backbuffer", "null", "none", 0, 0, 0, 0)
  Rasterize(_ARG_0_, "framebuffer0")
  Render2D(_ARG_0_)
end
