function Init(_ARG_0_)
  CreateGame(_ARG_0_)
  CreateGameMaster(_ARG_0_, "gm_prepro.lua", "scripts/event_prepro.lua")
  CreateLight(_ARG_0_, 0.2)
  CreateHavokRunner(_ARG_0_)
  CreateEntityPlacement(_ARG_0_, "placement/wap/set_wap_c_sonic.XML")
  CreateTerrain(_ARG_0_, "stage/wap/c/")
  CreatePlayer(_ARG_0_, -685.771, 333.125, -229.189, 0, "sonic_new.ini")
  LoadSceneEnvMap(_ARG_0_, "trash/cubemap_test.dds")
  CreatePath(_ARG_0_, "stage/wap/c/whiteacropolis_c_path.bin")
end
