CrisisCity.ShadowB = inherits_from(ActionArea)
function CrisisCity.ShadowB.constructor(_ARG_0_)
  ActionArea.constructor(_ARG_0_)
  Game.Log("construct CrisisCity.ShadowB")
end
function CrisisCity.ShadowB.Setup(_ARG_0_)
  ActionArea.Setup(_ARG_0_)
  Game.Log("CrisisCity.ShadowB.Setup")
  _ARG_0_:AddComponent({
    Game.LoadRenderScript("scripts/render/render_gamemode.lua"),
    Game.LoadTerrain("stage/csc/b/"),
    Game.LoadStageSet("scripts/mission/0102/set_cscB_shadow.xml"),
    Game.LoadStageSet("placement/csc/csc_mapB_effects.xml", "particle"),
    Game.LoadSceneParams("scripts/stage/csc/scene_csc_b.lua"),
    Game.LoadPath("placement/csc/path_cscB_shadow"),
    Game.LoadPath("placement/csc/grind_cscB_sonic", "grind"),
    Game.LoadPath("placement/csc/guide_cscB_sonic", "guide"),
    Game.LoadCameraSet("placement/csc/set_cscB_shadow.xml"),
    Game.LoadSoundBank("sound/stage_csc"),
    Game.LoadVoiceBank("sound/voice_csc_e"),
    Game.PlayBGM("stg_csc_b")
  })
  Game.SetPlayer(-15500, 22600, 59725, 90, "Shadow.lua")
end
function CrisisCity.ShadowB.cage01(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("common_cage01")
end
function CrisisCity.ShadowB.glassbreak001(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere201")
  Game.Signal("Physicsglass01")
end
function CrisisCity.ShadowB.glassbreak002(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere202")
  Game.Signal("Physicsglass02")
end
function CrisisCity.ShadowB.glassbreak003(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere203")
  Game.Signal("Physicsglass03")
end
function CrisisCity.ShadowB.glassbreak004(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere204")
  Game.Signal("Physicsglass04")
end
function CrisisCity.ShadowB.glassbreak005(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere205")
  Game.Signal("Physicsglass05")
end
function CrisisCity.ShadowB.glassbreak006(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere206")
  Game.Signal("Physicsglass06")
end
function CrisisCity.ShadowB.glassbreak007(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere207")
  Game.Signal("Physicsglass07")
end
function CrisisCity.ShadowB.glassbreak008(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere208")
  Game.Signal("Physicsglass08")
end
function CrisisCity.ShadowB.glassbreak009(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere209")
  Game.Signal("Physicsglass09")
end
function CrisisCity.ShadowB.glassbreak010(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere210")
  Game.Signal("Physicsglass10")
end
function CrisisCity.ShadowB.glassbreak011(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere211")
  Game.Signal("Physicsglass11")
end
function CrisisCity.ShadowB.glassbreak012(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere212")
  Game.Signal("Physicsglass12")
end
function CrisisCity.ShadowB.explosion_001(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("bldgexplode01")
  Game.Signal("impulsesphere01")
  Game.Signal("Physicsglass38")
  Game.Signal("Physicsglass39")
  Game.Signal("Physicsglass40")
  Game.Signal("Physicsglass42")
  Game.Signal("Physicsglass43")
  Game.Signal("Physicsglass44")
  Game.Signal("Physicsglass46")
  Game.Signal("Physicsglass47")
  Game.Signal("Physicsglass48")
end
function CrisisCity.ShadowB.explosion_002(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere02")
  Game.Signal("impulsesphere03")
  Game.Signal("impulsesphere04")
  Game.Signal("impulsesphere05")
  Game.Signal("impulsesphere06")
  Game.Signal("impulsesphere07")
  Game.Signal("impulsesphere08")
  Game.Signal("impulsesphere09")
  Game.Signal("impulsesphere10")
  Game.Signal("impulsesphere11")
  Game.Signal("impulsesphere12")
  Game.Signal("Physicsglass33")
  Game.Signal("Physicsglass34")
  Game.Signal("Physicsglass35")
  Game.Signal("Physicsglass36")
  Game.Signal("Physicsglass37")
  Game.Signal("Physicsglass41")
  Game.Signal("Physicsglass45")
  Game.Signal("Physicsglass49")
  Game.Signal("Physicsglass50")
  Game.Signal("Physicsglass51")
  Game.Signal("Physicsglass52")
end
function CrisisCity.ShadowB.explosion_003(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere13")
  Game.Signal("impulsesphere14")
  Game.Signal("impulsesphere15")
  Game.Signal("impulsesphere16")
  Game.Signal("impulsesphere17")
  Game.Signal("impulsesphere18")
  Game.Signal("impulsesphere19")
  Game.Signal("impulsesphere20")
  Game.Signal("Physicsglass29")
  Game.Signal("Physicsglass30")
  Game.Signal("Physicsglass31")
  Game.Signal("Physicsglass32")
  Game.Signal("Physicsglass53")
  Game.Signal("Physicsglass54")
  Game.Signal("Physicsglass55")
  Game.Signal("Physicsglass56")
end
function CrisisCity.ShadowB.explosion_004(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere21")
  Game.Signal("impulsesphere22")
  Game.Signal("impulsesphere23")
  Game.Signal("impulsesphere24")
  Game.Signal("impulsesphere25")
  Game.Signal("impulsesphere26")
  Game.Signal("impulsesphere27")
  Game.Signal("impulsesphere28")
  Game.Signal("Physicsglass25")
  Game.Signal("Physicsglass26")
  Game.Signal("Physicsglass27")
  Game.Signal("Physicsglass28")
  Game.Signal("Physicsglass57")
  Game.Signal("Physicsglass58")
  Game.Signal("Physicsglass59")
  Game.Signal("Physicsglass60")
end
function CrisisCity.ShadowB.explosion_005(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere29")
  Game.Signal("impulsesphere30")
  Game.Signal("impulsesphere31")
  Game.Signal("impulsesphere32")
  Game.Signal("impulsesphere33")
  Game.Signal("impulsesphere34")
  Game.Signal("impulsesphere35")
  Game.Signal("impulsesphere36")
  Game.Signal("Physicsglass21")
  Game.Signal("Physicsglass22")
  Game.Signal("Physicsglass23")
  Game.Signal("Physicsglass24")
  Game.Signal("Physicsglass61")
  Game.Signal("Physicsglass62")
  Game.Signal("Physicsglass63")
  Game.Signal("Physicsglass64")
  Game.Signal("impulsesphere69")
  Game.Signal("impulsesphere70")
  Game.Signal("impulsesphere71")
  Game.Signal("impulsesphere72")
  Game.Signal("impulsesphere73")
  Game.Signal("impulsesphere74")
  Game.Signal("impulsesphere75")
  Game.Signal("impulsesphere76")
  Game.Signal("Physicsglass69")
  Game.Signal("Physicsglass70")
  Game.Signal("Physicsglass71")
  Game.Signal("Physicsglass72")
  Game.Signal("Physicsglass109")
  Game.Signal("Physicsglass110")
  Game.Signal("Physicsglass111")
  Game.Signal("Physicsglass112")
end
function CrisisCity.ShadowB.explosion_006(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere37")
  Game.Signal("impulsesphere38")
  Game.Signal("impulsesphere39")
  Game.Signal("impulsesphere40")
  Game.Signal("Physicsglass65")
  Game.Signal("Physicsglass66")
  Game.Signal("Physicsglass67")
  Game.Signal("Physicsglass68")
  Game.Signal("impulsesphere77")
  Game.Signal("impulsesphere78")
  Game.Signal("impulsesphere79")
  Game.Signal("impulsesphere80")
  Game.Signal("Physicsglass113")
  Game.Signal("Physicsglass114")
  Game.Signal("Physicsglass115")
  Game.Signal("Physicsglass116")
end
function CrisisCity.ShadowB.BtoC(_ARG_0_)
  _ARG_0_:ChangeArea("Area C")
end
