CrisisCity.SilverB = inherits_from(ActionArea)
function CrisisCity.SilverB.constructor(_ARG_0_)
  ActionArea.constructor(_ARG_0_)
  Game.Log("construct CrisisCity.SilverB")
end
function CrisisCity.SilverB.Setup(_ARG_0_)
  ActionArea.Setup(_ARG_0_)
  Game.Log("CrisisCity.SilverB.Setup")
  _ARG_0_:AddComponent({
    Game.LoadRenderScript("scripts/render/render_gamemode.lua"),
    Game.LoadTerrain("stage/csc/b/"),
    Game.LoadStageSet("scripts/mission/0201/set_cscB_silver.XML"),
    Game.LoadStageSet("placement/csc/csc_mapB_effects.xml", "particle"),
    Game.LoadSceneParams("scripts/stage/csc/scene_csc_b.lua"),
    Game.LoadPath("scripts/mission/0201/path_cscB_silver"),
    Game.LoadPath("placement/csc/grind_cscB_sonic", "grind"),
    Game.LoadPath("placement/csc/guide_cscB_silver", "guide"),
    Game.LoadSoundBank("sound/stage_csc"),
    Game.LoadVoiceBank("sound/voice_csc_e"),
    Game.PlayBGM("stg_csc_b")
  })
  Game.SetPlayer(9739, 5598.5, -60245, -40, "Blaze.lua")
end
function CrisisCity.SilverB.cage01(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("common_cage01")
end
function CrisisCity.SilverB.cage02(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("common_cage02")
end
function CrisisCity.SilverB.explosion_001(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("bldgexplode01")
  Game.Signal("impulsesphere01")
  Game.Signal("Physicsglass38")
  Game.Signal("Physicsglass42")
  Game.Signal("Physicsglass46")
  Game.Signal("bldgexplode02")
  Game.Signal("impulsesphere41")
  Game.Signal("Physicsglass85")
  Game.Signal("Physicsglass89")
  Game.Signal("Physicsglass93")
end
function CrisisCity.SilverB.explosion_002(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere02")
  Game.Signal("impulsesphere03")
  Game.Signal("impulsesphere04")
  Game.Signal("impulsesphere05")
  Game.Signal("impulsesphere06")
  Game.Signal("impulsesphere07")
  Game.Signal("impulsesphere08")
  Game.Signal("impulsesphere09")
  Game.Signal("impulsesphere10")
  Game.Signal("impulsesphere11")
  Game.Signal("impulsesphere12")
  Game.Signal("Physicsglass33")
  Game.Signal("Physicsglass36")
  Game.Signal("Physicsglass45")
  Game.Signal("Physicsglass51")
  Game.Signal("impulsesphere42")
  Game.Signal("impulsesphere43")
  Game.Signal("impulsesphere44")
  Game.Signal("impulsesphere45")
  Game.Signal("impulsesphere46")
  Game.Signal("impulsesphere47")
  Game.Signal("impulsesphere48")
  Game.Signal("impulsesphere49")
  Game.Signal("impulsesphere50")
  Game.Signal("impulsesphere51")
  Game.Signal("impulsesphere52")
  Game.Signal("Physicsglass81")
  Game.Signal("Physicsglass84")
  Game.Signal("Physicsglass96")
  Game.Signal("Physicsglass99")
end
function CrisisCity.SilverB.explosion_003(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere13")
  Game.Signal("impulsesphere14")
  Game.Signal("impulsesphere15")
  Game.Signal("impulsesphere16")
  Game.Signal("impulsesphere17")
  Game.Signal("impulsesphere18")
  Game.Signal("impulsesphere19")
  Game.Signal("impulsesphere20")
  Game.Signal("Physicsglass29")
  Game.Signal("Physicsglass32")
  Game.Signal("Physicsglass55")
  Game.Signal("impulsesphere53")
  Game.Signal("impulsesphere54")
  Game.Signal("impulsesphere55")
  Game.Signal("impulsesphere56")
  Game.Signal("impulsesphere57")
  Game.Signal("impulsesphere58")
  Game.Signal("impulsesphere59")
  Game.Signal("impulsesphere60")
  Game.Signal("Physicsglass78")
  Game.Signal("Physicsglass102")
  Game.Signal("Physicsglass104")
end
function CrisisCity.SilverB.explosion_004(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere21")
  Game.Signal("impulsesphere22")
  Game.Signal("impulsesphere23")
  Game.Signal("impulsesphere24")
  Game.Signal("impulsesphere25")
  Game.Signal("impulsesphere26")
  Game.Signal("impulsesphere27")
  Game.Signal("impulsesphere28")
  Game.Signal("Physicsglass25")
  Game.Signal("Physicsglass28")
  Game.Signal("Physicsglass59")
  Game.Signal("impulsesphere61")
  Game.Signal("impulsesphere62")
  Game.Signal("impulsesphere63")
  Game.Signal("impulsesphere64")
  Game.Signal("impulsesphere65")
  Game.Signal("impulsesphere66")
  Game.Signal("impulsesphere67")
  Game.Signal("impulsesphere68")
  Game.Signal("Physicsglass73")
  Game.Signal("Physicsglass76")
  Game.Signal("Physicsglass107")
end
function CrisisCity.SilverB.explosion_005(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere29")
  Game.Signal("impulsesphere30")
  Game.Signal("impulsesphere31")
  Game.Signal("impulsesphere32")
  Game.Signal("impulsesphere33")
  Game.Signal("impulsesphere34")
  Game.Signal("impulsesphere35")
  Game.Signal("impulsesphere36")
  Game.Signal("Physicsglass21")
  Game.Signal("Physicsglass24")
  Game.Signal("Physicsglass63")
  Game.Signal("impulsesphere69")
  Game.Signal("impulsesphere70")
  Game.Signal("impulsesphere71")
  Game.Signal("impulsesphere72")
  Game.Signal("impulsesphere73")
  Game.Signal("impulsesphere74")
  Game.Signal("impulsesphere75")
  Game.Signal("impulsesphere76")
  Game.Signal("Physicsglass70")
  Game.Signal("Physicsglass109")
  Game.Signal("Physicsglass112")
end
function CrisisCity.SilverB.explosion_006(_ARG_0_, _ARG_1_)
  Game.Debug()
  Game.Signal("impulsesphere37")
  Game.Signal("impulsesphere38")
  Game.Signal("impulsesphere39")
  Game.Signal("impulsesphere40")
  Game.Signal("Physicsglass65")
  Game.Signal("Physicsglass67")
  Game.Signal("impulsesphere77")
  Game.Signal("impulsesphere78")
  Game.Signal("impulsesphere79")
  Game.Signal("impulsesphere80")
  Game.Signal("Physicsglass113")
  Game.Signal("Physicsglass115")
end
function CrisisCity.SilverB.BtoF2(_ARG_0_)
  _ARG_0_:ChangeArea("Area F2")
end
